############# English navigation ##############

# main menu
[[main]]
name = "Services"
url = "service/"
weight = 1

[[main]]
name = "Customers"
url = "project/"
weight = 2

[[main]]
name = "About"
url = "about/"
weight = 3

# footer menu
[[footer]]
name = "Terms of Service"
url = "terms/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2